name: Deploy Private GitHub repository to our server
on:
  push:
    branches:
      - sagor
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.project.expertvence.com
          username: u847662062.apps
          password: "y1W4N7wMgH;Bk9|X"
          exclude: |

            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/stubs/**
