name: Deploy Website on Every Commit
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v2
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.sunriseloan.expertvence.com
          username: u847662062.sunriseloan
          password: "F0#Y@h$*$io?H9?i"
         

        