name: Deploy Private GitHub repository to our server

on:
  push:
    branches:
      - version_1

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.project.expertvence.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/stubs/**